import React from 'react'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from '../../utils/providers/Providers';
import { AlertProvider } from '../users/context/AlertContext';
import Head from 'next/head';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Provider>
            <AlertProvider>
              {children}
            </AlertProvider>
          </Provider>
      </body>
    </html>
  );
}
